version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:20.10

jobs:
  build:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker images using Docker Compose
          command: |
            docker-compose -f docker-compose-build.yaml build
      - run:
          name: Login to DockerHub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Tag and Push Docker images to DockerHub
          command: |
            docker tag reverseproxy quanterran/reverseproxy:v1
            docker tag udagram-api-user quanterran/udagram-api-user:v1
            docker tag udagram-api-feed quanterran/udagram-api-feed:v1
            docker tag udagram-frontend quanterran/udagram-frontend:v2
            docker push quanterran/reverseproxy:v1
            docker push quanterran/udagram-api-user:v1
            docker push quanterran/udagram-api-feed:v1
            docker push quanterran/udagram-frontend:v2
 
workflows:
  version: 2
  build-deploy:
    jobs:
      - build